#!/bin/bash

set -e

link_files() {
    echo "Linking config files"

    if [ ! -d "$HOME/.config" ]; then
	mkdir $HOME/.config
    fi

    for dir in $(find user/* -type d)
    do
	d=$(basename $dir)
	if [ -L ${HOME}/.config/${d} ]
	then
	    echo "$d already linked. Skipping."
	else
        echo "Linking $d"
	    ln -sf $(pwd)/$dir $HOME/.config/$d
	fi
    done

    echo "Linking config for ZRAM service (may require sudo password)"
    /usr/bin/sudo ln -sf $(pwd)/etc/scripts /etc/scripts
    /usr/bin/sudo ln -sf $(pwd)/etc/systemd/system/zram.service /etc/systemd/system/zram.service
    echo ""
    echo "Enabling ZRAM service"

    /usr/bin/sudo systemctl enable --now zram.service
}

install_yay() {
    if ! command -v yay >/dev/null 2>&1; then
        echo "yay command not found. Installing yay"

        folder=$(mktemp -d)
        /usr/bin/git clone https://aur.archlinux.org/yay $folder
        pushd $folder
        makepkg -si
        popd
        rm -rf $folder
    fi
}

install_packages() {
    echo "Installing packages"
    packages=""

    while read -r line; do
        packages="$packages $line"
    done < ".packagelist"

    /usr/bin/yay -S --needed $packages
}

install_st() {
    echo "Compiling and installing st (simple terminal)"
    folder=$(mktemp -d)
    /usr/bin/git clone https://github.com/CommandMaker/st $folder
    pushd $folder
    /usr/bin/sudo make install
    popd
    rm -rf $folder
}

main() {
    link_files
    install_yay
    install_packages
    #install_st
}


main
